
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css"
import { Toaster } from "@/components/ui/sonner"
import Providers from "../provider/Providers";
import Footer from "./_components/Footer/Footer";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title> Fresh Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background font-sans flex flex-col`}
      >

        <Providers>
          <Navbar />
          <main className="flex-grow">
            {children}
          </main>
          <Toaster
            position="top-center"
            offset="58px"
            toastOptions={{
              style: {
                background: "#111827",   // dark elegant
                color: "#fff",
                border: "1px solid #1f2937",
                padding: "14px 16px",
                borderRadius: "12px",
                boxShadow: "0 10px 25px rgba(0,0,0,0.15)"
              }
            }}
          />
          <Footer />
        </Providers>

      </body>
    </html>
  );
}
